# Generated by Django 5.2.8 on 2025-11-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre_o_tutor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('PLAY_SCHOOL', 'PLAY SCHOOL'), ('CHILDREN', 'CHILDREN'), ('KIDS_1', 'KIDS 1'), ('KIDS_2', 'KIDS 2'), ('KIDS_3', 'KIDS 3'), ('JUNIORS_1', 'JUNIORS 1'), ('JUNIORS_2', 'JUNIORS 2'), ('JUNIORS_3', 'JUNIORS 3'), ('JUNIORS_4', 'JUNIORS 4'), ('1ST_INTENSIVE', '1st INTENSIVE'), ('3RD_INTENSIVE', '3rd INTENSIVE'), ('5TH_INTENSIVE', '5th INTENSIVE'), ('6TH_INTENSIVE', '6th INTENSIVE'), ('7TH_INTENSIVE', '7th INTENSIVE'), ('CRASH_1', 'CRASH 1'), ('CRASH_2', 'CRASH 2')], max_length=30),
        ),
    ]
