# Generated by Django 5.2.8 on 2025-12-07 21:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_fecha_nacimiento_alumno_padre_o_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='concepto_pago',
            field=models.CharField(choices=[('Mensualidad', 'Mensualidad'), ('Materiales', 'Materiales'), ('Examen', 'Examen'), ('Inscripción', 'Inscripción')], default='Mensualidad', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='mes_correspondiente',
            field=models.CharField(blank=True, help_text="Ej: 'Noviembre 2025'. Opcional.", max_length=30),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_examen', models.CharField(max_length=150)),
                ('fecha_examen', models.DateField()),
                ('calificacion_obtenida', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumnos.alumno')),
            ],
        ),
    ]
