# Generated by Django 5.2.8 on 2025-12-14 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_correo_electronico_alumno_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion_obtenida',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
