# Generated by Django 5.2.8 on 2025-12-14 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_calificacion_calificacion_obtenida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion_obtenida',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
